openapi: 3.0.1
info:
  title: gaqqie provider API
  contact:
    email: tknsryk@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
externalDocs:
  description: gaqqie provider API
  url: https://github.com/gaqqie/gaqqie-sky/blob/main/app/gaqqie-provider-api.yaml
paths:
  /v1/jobs/{device_name}:
    get:
      tags:
      - job
      operationId: receive_job
      parameters:
      - name: device_name
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/job'
        404:
          description: job not found
          content: {}
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProdiverApiReceiveJobLambdaFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
  /v1/results/{job_id}:
    post:
      tags:
      - job
      operationId: register_result
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/result'
        required: true
      responses:
        200:
          description: successful operation
          content: {}
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProdiverApiRegisterResultLambdaFunction.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
components:
  schemas:
    job:
      #required:
      #- id
      type: object
      properties:
        id:
          type: string
          description: a unique id of job
        name:
          type: string
        provider_name:
          type: string
        device_name:
          type: string
        create_time:
          type: string
        instructions:
          type: string
    result:
      required:
      - job_id
      type: object
      properties:
        job_id:
          type: string
          description: a unique id of job result
        status:
          type: string
          enum:
          - SUCCEEDED
          - FAILED
        end_time:
          type: string
        results:
          type: string
